### ISSUE TITLE
Отступы.

### ISSUE THREAD

**Issue by ridouchire** [kugimiya/kugicsdock#1]
https://github.com/kugimiya/kugicsdock/blob/9cb7198bdbd7f6adee632f31a55f67a68989e8d8/etc/nginx/vhost.conf#L21

Всё пропало, всё разъехалося.

**Comment by kugimiya** [comment]
ебать здраститя

**Comment by ridouchire** [comment]
PR - https://github.com/kugimiya/kugicsdock/pull/2

**Comment by kugimiya** [comment]
Замержил, можно наверно и закрыть

**Comment by ridouchire** [comment]
Мержи лучше сквошем, чтобы мерж-коммита не было - только коммит изменений. Будет история в репозитории красивой и шелковистой. :3

**Comment by kugimiya** [comment]
no sense
